# Generated by Django 5.0.4 on 2024-06-12 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home_admission',
            old_name='able_to_act_independently',
            new_name='act_independently',
        ),
        migrations.AlterField(
            model_name='login_info',
            name='log_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 15, 37, 42, 471673)),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 15, 37, 42, 469674)),
        ),
    ]
