# Generated by Django 5.0.4 on 2024-07-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='create_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='privilege',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='userid',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
