# Generated by Django 5.0.4 on 2024-06-26 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 12, 7, 28, 158306)),
        ),
    ]
