# Generated by Django 5.0.4 on 2024-06-07 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_info',
            name='log_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 16, 56, 55, 616912)),
        ),
        migrations.AlterField(
            model_name='login_info',
            name='log_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='nurse_duty',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 16, 56, 55, 615912)),
        ),
    ]
