# Generated by Django 5.0.4 on 2024-06-15 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_info',
            name='log_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 17, 6, 1, 768684)),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 17, 6, 1, 767684)),
        ),
    ]
