# Generated by Django 5.0.4 on 2024-06-17 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0002_alter_login_info_log_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse_duty',
            name='by_whom',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='nurse_duty',
            name='designation',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='login_info',
            name='log_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 11, 44, 7, 283190)),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 11, 44, 7, 282191)),
        ),
    ]
