# Generated by Django 5.0.4 on 2024-07-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0002_alter_user_details_create_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='privilege',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
