# Generated by Django 5.0.4 on 2024-06-17 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0003_nurse_duty_by_whom_nurse_duty_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_info',
            name='log_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 13, 38, 48, 805014)),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 13, 38, 48, 804012)),
        ),
    ]
